# 基于期约链的异步编程技术

[[toc]]

## 期约

### 什么是期约

期约是一种新的异步编程技术，使用期约可以实现链式调用，可以解决回调地狱的问题。、
期约链的本质就是产生期约 1->期约 1 落地（兑现或拒绝）->处理期约 1 落地的结果->产生新期约 2->期约 2 落地->继续处理新期约 2 的结果->产生新期约 3 以此类推

### 创建期约对象

创建期约对象只需要调用 Promise 构造函数并传入一个执行器函数作为参数即可。

```javascript
// 嗲用构造函数传入执行器函数
const promise = new Promise((resolve, reject) => {
  // 执行器函数中进行异步操作
});
```

### 期约对象的三种状态

对于创建的每个期约对象，都有三种状态，如下所示：

1. 待定状态（pending）：异步操作未完成
2. 解决状态（fulfilled）：异步操作成功完成
3. 拒绝状态（rejecte2）：异步操作失败

其新创建的期约对象状态默认为 pending 状态

```javascript
// 使用new Promise构造函数创建期约对象并传入执行器函数
const promise = new Promise((resolve, reject) => {});
console.log(promise);
```

![pending状态](https://image-bucket-1307756649.cos.ap-chengdu.myqcloud.com/image/20250621152802510.png)

### 期约对象的状态的转变

期约对象的状态是可以发生变化的，但变化途径只有两个

1. 从**待定**到**解决**
2. 从**待定**到**拒绝**

也就是说期约落地，状态就不再改变了。这也意味着 Promise 实例的状态变化只可能发生一次。

而这一系列的状态转变都发生在执行器函数中，即通过传入执行器函数的 resolve 或 reject 方法来改变状态。

1. 使用 resolve 方法将期约状态从 pending 变为 fulfilled
2. 使用 reject 方法将 qi 约状态从 pending 变为 rejected

```js
function myajax() {
  return new Promise((resolve, reject) => {
    // 发送io请求
    // 发送解决将期约状态从 pending 变为 fulfilled
    resolve();
    // 发送拒绝将期约状态从 pending 变为 rejected
    reject();
  });
}
myajax().then().catch();
```

![期约落地](https://image-bucket-1307756649.cos.ap-chengdu.myqcloud.com/image/20250621153517900.png)

### 期约落地时传递数据

在期约状态转变时可以传递一个值，这个值作为期约落地的结果。如下所示：

1. resolve 方法可以将该期约对象的状态从 pending 变为 fulfilled，并传递一个值作为期约兑现的结果

```javascript
let promise1 = new Promise((resolve, reject) => {
  // 发送io请求解决
  resolve({ data: [], msg: '', code: '' });
});
console.log(promise1);
```

![兑现的结果](https://image-bucket-1307756649.cos.ap-chengdu.myqcloud.com/image/20250621155755788.png)

2. reject 方法可以将该期约对象的状态从 pending 变为 rejected，并传递一个值作为期约拒绝的原因

```javascript
let promise2 = new Promise((resolve, reject) => {
  reject({ msg: '数据请求拒绝', code: 401 });
});
console.log(promise2);
```

![拒绝的结果](https://image-bucket-1307756649.cos.ap-chengdu.myqcloud.com/image/20250621155828561.png)

### 对期约结果的处理

使用 promise 对象的 then 方法和 catch 方法可以对期约结果进行处理。只不过 then 方法既可以处理兑现的情况又可以处理拒绝的情况。而 catch 方法只处理拒绝的情况。

1. 使用 then 方法可以传入两个参数，第一个参数是处理期约兑现时的回调函数，第二个参数是处理期约拒绝时的回调函数。
2. 使用 catch 方法可以传入一个参数，参数是处理期约拒绝时的回调函数。

比如下面的案例：
::: code-group

```js [promise]
const promise = new Promise((resolve, reject) => {
  const success = true; // 改为 false 会触发失败

  if (success) {
    resolve('操作成功!');
  } else {
    reject('操作失败!');
  }
});
```

```js [then]
promise.then(
  result => {
    // 处理兑现的情况
    console.log('成功:', result);
  },
  error => {
    // 处理拒绝的情况
    console.log('失败:', error);
  },
);
```

```js [catch]
promise
  .then(result => {
    // 处理兑现的情况
    console.log('成功:', result);
  })
  .catch(error => {
    // 处理拒绝的情况
    console.log('捕获失败:', error);
  });
```

:::

::: tip 关于这两个方法的返回值
then 方法返回值：

- 如果回调返回 ​ 普通值（非 Promise）​​ → 新 Promise 变为 ​fulfilled，携带该值
- 如果回调返回 ​fulfilled 的 Promise​ → 新 Promise 同样变为 ​fulfilled，携带该 Promise 的值
- 如果回调返回 ​rejected 的 Promise​ → 新 Promise 变为 ​rejected，携带该 Promise 的错误
- 如果回调 ​ 抛出异常（throw）​​ → 新 Promise 变为 ​rejected，携带该错误

catch 方法返回值：​ 本质是 then(null, onRejected) 的语法糖，同样返回新 Promise

也就是说无论是调用 then 还是 catch，返回的都是新的 promise 对象，不会影响原来的 promise 对象。以此就可以实现链式调用，也就是后面讲的期约链
:::

:::warning catch 和 then 的运行方式

- then(onFulfilled, onRejected) 的第二个参数（onRejected）会优先捕获错误。
- catch(onRejected) 只有在之前的 then 没有提供 onRejected 时才会触发

:::

## 期约的类方法

期约还有许多的类方法

### Promise.resolve

将现有数据（无论什么类型）包装为 fulfilled 状态的 Promise 对象。

```javascript
// 调用原型上的resolve方法
const p1 = Promise.resolve('lmh');
// 等价于
const p2 = new Promise(resolve => resolve('lmh'));
console.log(p1);
console.log(p2);
```

### Promise.reject

将现有数据（无论什么类型）包装为 rejected 状态的 Promise 对象

```javascript
const p1 = new Promise((resolve, reject) => {
  resolve();
});
const p2 = Promise.reject(p1);
console.log(p1);
console.log(p2);
```

### Promise.all

`Promise.all()`方法用于将多个 Promise 实例，包装成一个新的 Promise 实例。
`const p = Promise.all([p1, p2, p3]);`其中 `p1,p2,p3` 都是 promise 对象 p 的状态由 `p1,p2,p3` 决定，分成两种情况。

1. 只有 `p1、p2、p3` 的状态都变成 fulfilled，那么调用 `Promise.all()`方法后返回的 p 的状态才会变成 `fulfilled`，此时 `p1、p2、p3` 的返回值会组成一个数组，传递给 p 的回调函数。
2. 只要 `p1、p2、p3` 之中有一个被 rejected，p 的状态就变成 `rejected`，此时第一个被 reject 的实例的返回值，会传递给 p 的回调函数。

```javascript
function ajax(url) {
  //...
}
let list = ['kerwin', 'tiechui'];
// 将list中的每个元素映射为promise对象，并放入新数组
let promiseList = list.map(item => ajax(`http://localhost:3000/news?author=${item}`));
// Promise.all()方法用于将多个 Promise 实例，包装成一个新的 Promise 实例。
let promises = Promise.all(promiseList);
promises
  .then(dataList => {
    console.log(dataList);
  })
  .catch(error => {
    console.log(error);
  });
```

![Promise.all](https://image-bucket-1307756649.cos.ap-chengdu.myqcloud.com/image/20250621161232713.png)

::: tip 提示
若期约数组中其中一个不是期约对象，那么它就会被当作一个已兑现的期约值，被原封不动的复制到输出数组中
:::

### Promise.race

`Promise.race()`方法同样是将多个 Promise 实例，包装成一个新的 Promise 实例。

```javascript
const p = Promise.race([p1, p2, p3]);
```

上面代码中，只要`p1、p2、p3`之中有一个实例率先改变状态，p 的状态就跟着改变。那个率先改变的 Promise 实例的返回值，就传递给 p 的回调函数。

应用场景如下：

1. 为 ajax 设置请求超时，当发起请求是同时设定一个定时器，若在定时器指定时间没有收到响应那么表示请求超时返回拒绝的 promise

```javascript
function ajax(url, time = 1000) {
  // 若路径不对返回rejected状态的promise对象
  if (url === '') {
    throw new Error('路径不合法');
    // return Promise.reject()
  }
  // 获取缓存
  let cache = ajax.cache || (ajax.cache = { data: null });
  // 判定缓存中有是否有数据，有数据从缓存中获取数据
  if (cache.data) {
    // 返回promise对象
    return Promise.resolve(cache.data);
  }
  // 无数据请求数据
  const p1 = new Promise((resolve, reject) => {
    let xhr = new XMLHttpRequest();
    xhr.open('get', url, true);
    xhr.send();
    xhr.onreadystatechange = function () {
      if (xhr.readyState === 4) {
        if (xhr.status >= 200 && xhr.status < 300) {
          resolve(JSON.parse(xhr.responseText));
          // 将数据缓存
          ajax.cache.data = xhr.responseText;
        } else {
          reject(xhr.responseText);
        }
      }
    };
  });
  // 设置定时器，若发出请求时间超过定时器设定时间那么返回拒绝状态的promise，表示请求超时
  const p2 = new Promise((resolve, reject) => {
    setTimeout(() => {
      reject('超时');
    }, time);
  });
  return Promise.race([p1, p2]);
}
ajax('./test.json', 1)
  .then(res => {
    console.log(res);
  })
  .catch(error => {
    console.log(error);
  });
```

2. 可以同时请求多态服务器，当一台挂掉的时候会返回另一请求解决的 promise

### Promise.allSettled

`Promise.allSettled()` 是 `Promise.all()` 的改进版，它不会因为某个 Promise 被拒绝而短路，而是会等待所有 Promise 都完成（无论成功或失败,allSettled 为全部落地的意思），最终返回一个包含每个 Promise 结果的对象数组。这样你就可以在一个统一的 `.then()` 中处理所有结果，而不需要进入 `.catch()`。

- 兑现的结果通过 value 属性获取
- 拒绝的原因通过 reason 属性获取

```javascript
Promise.allSettled([
  Promise.resolve('成功1'),
  Promise.reject('失败'),
  Promise.resolve('成功2'),
]).then(results => {
  const successes = results.filter(r => r.status === 'fulfilled').map(r => r.value);
  const errors = results.filter(r => r.status === 'rejected').map(r => r.reason);

  console.log('成功的请求:', successes); // ['成功1', '成功2']
  console.log('失败的请求:', errors); // ['失败']
});
```

### Promise.any

只要参数实例有一个变成 fulfilled 状态，包装实例就会变成 fulfilled 状态；如果所有参数实例都变成 rejected 状态，包装实例就会变成 rejected 状态。
应用场景：假如登录一个会员联盟系统，这时候登录会员联盟的任意一个解决都算解决，那么就算解决，比如腾讯视频、爱奇艺、酷米视频三家会员联盟登录解决一个其它都算登录解决

```javascript
const p1 = new Promise((resolve, reject) => {
  setTimeout(() => {
    reject('腾讯视频登录拒绝');
  }, 1000);
});
const p2 = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve('爱奇艺视频登录解决');
  }, 2000);
});
const p3 = new Promise((resolve, reject) => {
  setTimeout(() => {
    reject('酷米视频登录拒绝');
  }, 3000);
});
const promises = [p1, p2, p3];
Promise.any(promises)
  .then(res => {
    console.log('登录解决');
    // 跳转主页
  })
  .catch(error => {
    console.log('登录拒绝');
  });
```

### Promise.finally

finally 方法无论 promise 什么状态都会执行（ES9 中的新特性）

应用场景：通常在这个方法中释放资源，比如发出请求后显示加载器，等数据回来后隐藏加载器就可以在 finally 中进行

```javascript
const promise = new Promise((resolve, reject) => {
  console.log('loading中');
  setTimeout(() => {
    reject('请求数据');
  }, 1000);
});
promise
  .then(res => {
    console.log(res);
  })
  .catch(error => {
    console.log(error);
  })
  .finally(() => {
    console.log('隐藏loading');
  });
```

## 期约链

### 期约链的本质

期约链的本质就是产生期约 1->期约 1 落地（兑现或拒绝）->处理期约 1 落地的结果->产生新期约 2->期约 2 落地->继续处理新期约 2 的结果->产生新期约 3 以此类推

期约的落地和产生的关键在于 then 和 catch 方法

- 期约的兑现处理是在 then 方法第一个回调函数中进行的
- 期约的拒绝处理是在 then 方法的第二个回调函数或 catch 的第一个回调函数中进行的
- 新期约 then 和 catch 方法执行返回的结果

:::tip 下面用买彩票的案例来说明期约链的应用
期约 1：买第一张彩票，50%概率中奖
期约 1 落地处理：

- 若中奖（兑现） → 买第二张彩票，50%概率中奖（期约 1 兑现的结果是在 then 方法第一个回调函数中进行的处理的，期约 2 是 then 方法调用后的结果）
- 若未中奖（拒绝） → 直接止损（期约 1 拒绝的结果是在 catch 或 then 方法第二个回调函数中进行的处理的，期约 2 是 catch 或 then 方法调用后的结果）

期约 1 落地处理后产生新期约 2：

- 若中奖（兑现） → 点到位为止（then 方法第一个回调函数中进行的）
- 若未中奖（拒绝） → 直接止损（then 方法第二个回调函数中或 catch 方法中进行的）

...

:::

```javascript
// 模拟买彩票：50%概率中奖（返回"中奖"或"未中奖"）
function buyLottery() {
  return new Promise((resolve, reject) => {
    const isWin = Math.random() > 0.5; // 50%中奖概率
    setTimeout(() => {
      isWin ? resolve('中奖') : reject('未中奖');
    }, 1000); // 模拟异步操作
  });
}

// 初始期约：买第一张彩票
buyLottery()
  // 期约1落地处理：中奖则买第二张（then第一个回调）
  .then(result => {
    console.log(`第一张彩票结果：${result}`);
    console.log('继续买第二张彩票...');
    return buyLottery(); // 返回新期约（期约2）
  })
  // 期约2落地处理：中奖则停止（then第一个回调）
  .then(result => {
    console.log(`第二张彩票结果：${result}`);
    console.log('连续中奖，收手！');
  })
  // 统一处理任何阶段的拒绝（catch）
  .catch(error => {
    console.log(`彩票结果：${error}`);
    console.log('未中奖，立即止损！');
  });
```

![买彩票案例](https://image-bucket-1307756649.cos.ap-chengdu.myqcloud.com/image/20250621190625400.png)

### 重新封装 AJAX 解决回调地狱

```javascript
export function PromiseAjax({
  url,
  method = 'GET',
  data = null,
  headers = {},
  timeout = 3000,
  async = true,
}) {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();

    // 设置超时
    xhr.timeout = timeout;
    xhr.ontimeout = () => reject(new Error('请求超时'));

    // 初始化请求
    xhr.open(method, url, async);

    // 设置请求头
    for (const key in headers) {
      xhr.setRequestHeader(key, headers[key]);
    }

    // 发送请求
    xhr.send(data);

    // 处理响应
    xhr.onreadystatechange = function () {
      if (xhr.readyState === 4) {
        if (xhr.status === 200) {
          try {
            // 尝试解析 JSON（如果是 JSON 数据）
            const response = xhr.responseText ? JSON.parse(xhr.responseText) : xhr.responseText;
            resolve(response);
          } catch (e) {
            resolve(xhr.responseText); // 非 JSON 数据直接返回
          }
        } else {
          reject(new Error(xhr.statusText || '请求失败'));
        }
      }
    };

    // 处理网络错误
    xhr.onerror = () => reject(new Error('网络错误'));
  });
}

/**
 * 函数记忆化（缓存函数的执行结果）
 * @param {Function} fn 要缓存的函数对象
 * @returns {Function} 新的函数
 */
export function memoize(fn) {
  let cache = new Map();

  return function (...args) {
    // 检查是否要使用缓存（默认使用）
    let useCache = true;

    // 如果有额外控制参数（最后一个参数是布尔值）
    if (args.length > 0 && typeof args[args.length - 1] === 'boolean') {
      useCache = args.pop(); // 取出控制参数
    }

    // 序列化参数作为key
    const key = JSON.stringify(args);

    // 如果使用缓存且缓存存在
    if (useCache && cache.has(key)) {
      return cache.get(key);
    }

    // 计算新结果
    const result = fn.apply(this, args);
    cache.set(key, result);
    return result;
  };
}
```

使用演示

```javascript
const memoizedPromiseAjax = memoize(PromiseAjax);

window.onload = async function () {
  try {
    const response = await memoizedPromiseAjax({
      url: 'http://localhost:3000/users',
      method: 'GET',
    });
    console.log(response);
  } catch (error) {
    console.log(error.message);
  }
};
```

## async

可以看到先前的案例中，我们已经使用 promise 实现了链式调用，解决了回调地狱的问题，但是还是不够优雅。每个 then 方法需要手动返回一个新的 promise 对象，这让代码显得很冗余。
ES7 中引入了 async/await，可以让异步操作更加方便。async/await 就是 promise 的语法糖，它让异步操作更加像同步操作，而且更容易理解。

### 什么是 async

async 是用来声明函数的关键字，被 async 关键字声明的函数表示是一个异步函数其内部可能有异步操作，并且使用了该关键字的函数该一定会返回一个 Promise 实例对象。这样就不用我们 new Promise 了，但是对于声明 async 关键字的函数，对于不同的情况，返回的 promise 实例的状态也不同，下面有 5 大场景：

### 没有返回值但正常执行

1. 若函数没有返回值，且函数执行没有错误：函数执行后会默认返回一个不带数据的 fulfilled 状态的 promise 对象

```javascript
async function test() {}
let res = test();
console.log(res); // 没有携带数据的promise
```

![函数没有返回值，正常运行](https://image-bucket-1307756649.cos.ap-chengdu.myqcloud.com/image/20250621193623939.png)

### 没有返回值且抛出错误

2. 若函数无返回值，且函数有执行错误或手动抛出了错误：返回的是 rejected 状态的 Promise 对象

```javascript
async function test() {
  throw new Error('手动抛出错误');
}
let res = test();
console.log(res); // 带有错误信息的rejected状态的promise
```

![无返回值抛出错误](https://image-bucket-1307756649.cos.ap-chengdu.myqcloud.com/image/20250621193736440.png)

### 返回基本数据类型或对象数据

3. 返回基本数据类型或对象数据：实际返回以该基本类型或对象数据为数据的 fulfilled 状态的 promise 对象

```javascript
async function test() {
  return 'test';
}
let res = test();
console.log(res); // 以该字符串为数据的fulfilled状态的promise对象
```

![返回基本数据类型数据](https://image-bucket-1307756649.cos.ap-chengdu.myqcloud.com/image/20250621194147453.png)

### 返回 fulfilled 状态的 promise 对象

4. 返回 fulfilled 状态的 promise 对象：那么就是这个对象

```javascript
async function test() {
  return Promise.resolve('hello');
}
let res = test();
console.log(res);
```

![返回fulfilled状态的promise对象](https://image-bucket-1307756649.cos.ap-chengdu.myqcloud.com/image/20250621194249534.png)

### 返回 rejected 状态的 Promise 对象

5. 若有返回值，且返回 rejected 状态的 Promise 对象: 那么就是这个对象

```javascript
async function test() {
  return Promise.reject(new Error('error'));
}
let res = test();
console.log(res);
```

![回rejected状态的Promise对象](https://image-bucket-1307756649.cos.ap-chengdu.myqcloud.com/image/20250621195213941.png)

## await

await 与 async 一样都是关键字，像其语义“等待”一样，await 要求我们代码的执行时需要等待上一步异步操作执行完成才能执行下一个异步操作。当然 await 的作用不仅于此，它可以类似于 then 方法一样获取 promise 的结果值

### await 解构 promise 对象结果值

await 关键字必须要配合 async 关键字使用

#### 对解决状态的 promise 对象的处理

await 的作用之一在于解构解决状态下的 promise 对象，使我们能够直接拿到解决状态下的 promise 对象中的结果值，可以把它视为 then 函数的语法糖，方便我们的取值操作，如下案例：
若不使用 await 操作获取解决状态的 promise 对象值，则需要在获取 promise 对象后又调用其 then 方法，在 then 方法的回调函数中获取 promise 对象的结果值

```javascript
async function demo() {
  const promise = new Promise((resolve, reject) => {
    resolve('数据');
  });
  promise
    .then(res => {
      console.log(res);
    })
    .catch(error => {
      console.log(error);
    });
}
demo();
```

而使用 await 获取 promise 对象值时就不需要这么麻烦了，我们可以直接获取 fulfilled 状态的 promise 对象的结果值

```javascript
async function demo() {
  const data = await new Promise((resolve, reject) => {
    resolve('数据');
  });
  console.log(data); // 数据
}
demo();
```

#### 对拒绝状态 promise 对象的处理

若 await 后面的异步操作返回拒绝状态的 promise 对象，那么 await 会抛出错误来表示异步操作执行拒绝，我们可以使用 try/catch 来捕获处理异常，如下案例：

```javascript
async function demo() {
  try {
    const data = await new Promise((resolve, reject) => {
      reject(new Error('出错了'));
    });
  } catch (error) {
    console.log(error);
  }
}
demo();
```

![对拒绝状态 promise 对象的处理](https://image-bucket-1307756649.cos.ap-chengdu.myqcloud.com/image/20250621201356461.png)

#### 非 promise 对象的处理

当然若 await 后面非异步操作，而是数值则直接获取值，如下案例：

```javascript
async function demo() {
  const data = await 100;
  console.log(data); // 100
}
```

### await 的阻塞作用

#### 不使用 await 的代码执行顺序

await 也是一个关键字，就如同其语义一样，就是要等待异步执行结果。在没有使用 await 时，若遇到同步代码和异步代码同时出现，一定是先执行同步，再执行异步，比如下面的案例：

```javascript
function demo() {
  console.log('111');
  setTimeout(() => {
    console.log('异步函数执行了');
  }, 3000);
  console.log('333');
}
demo();
console.log('222');
```

执行结果为：
![不使用await的代码执行顺序](https://image-bucket-1307756649.cos.ap-chengdu.myqcloud.com/image/20250621201650630.png)

可以看到上面的代码会将 demo 中的同步代码执行完成后，然后打印'222'，最后再执行异步代码打印'异步函数执行了'，这样的后果就是我们不能够根据上一个异步操作的结果来进行后序异步操作

#### 使用 await 的代码执行顺序

若是使用了 await，就像是其语义“等待”一样，await 后面的代码若是异步操作，则会等待这一步异步操作完毕后再执行下面的语句，也就是将 demo 函数的执行进行阻塞，转而执行打印了“222”后，等到异步操作完成再继续执行 demo 函数执行，案例如下：

```javascript
async function demo() {
  console.log('111');
  await new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve('ok');
      console.log('异步函数执行了');
    }, 3000);
  });
  console.log('333');
}
demo();
console.log('222');
```

![不使用await的代码执行顺序](https://image-bucket-1307756649.cos.ap-chengdu.myqcloud.com/image/20250621201911534.png)

:::tip 总结
就是当函数出现异步代码时，若不使用 await 那么函数中的异步代码就会被跳过，执行函数剩下的代码，若使用了 await 那么函数内部就会等待函数中的异步代码执行完成后再执行函数中的剩余代码
:::

## async 和 await 的结合使用

::: warning 注意事项
await 通常与 aysnc 来一起使用，但是用 async 声明的函数内部不一定要有 await，反之函数内部有 await 则函数必须要用 async 声明
:::

### 不使用 async 和 await

就是将回调地狱变为了链式写法

```javascript
function ajax(url, time = 1000) {
  //...
}
let name = 'kerwin';
ajax(`http://localhost:3000/news?author=${name}`)
  .then(res => {
    const id = res[0].id;
    return ajax(`http://localhost:3000/commons?newsId=${id}`);
  })
  .then(res => {
    console.log(res);
  })
  .catch(error => {
    console.log(error);
  });
```

### 使用 async 和 await

这个就是类似于上面调用的语法糖

```javascript
async function getData() {
  let name = 'kerwin';
  try {
    // 等待该异步操作执行完成后在执行后序语句
    const res = await ajax(`http://localhost:3000/news?author=${name}`);
    const id = res[0].id;
    const data = await ajax(`http://localhost:3000/commons?newsId=${id}`);
    console.log(data);
  } catch (error) {
    console.log(error);
  }
}
```

## 手写一个 Promise
